# Generated by Django 5.2.6 on 2025-10-01 21:04

import django.core.validators
import django.db.models.deletion
import users.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('surname', models.CharField(blank=True, max_length=150, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), users.validators.validate_image])),
                ('name_displayed', models.CharField(blank=True, max_length=75, null=True)),
                ('score', models.PositiveIntegerField(default=0)),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('streak', models.IntegerField(default=0)),
                ('daily_goal_minutes', models.PositiveIntegerField(default=25)),
                ('daily_goal_score', models.PositiveIntegerField(default=10)),
                ('localization', models.CharField(blank=True, max_length=100, null=True)),
                ('country_of_origin', models.CharField(blank=True, max_length=100, null=True)),
                ('purpose_language', models.CharField(blank=True, max_length=100, null=True)),
                ('account_created_at', models.DateTimeField(auto_now_add=True)),
                ('tasks_confirmed', models.PositiveIntegerField(default=0)),
                ('course_studied', models.ManyToManyField(related_name='students', to='courses.course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
