# Generated by Django 5.2.6 on 2025-09-04 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=150)),
                ('avatar', models.ImageField(upload_to='avatars/')),
                ('name_displayed', models.CharField(max_length=75)),
                ('score', models.PositiveIntegerField(default=0)),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('streak', models.IntegerField(default=0)),
                ('daily_goal_minutes', models.PositiveIntegerField(default=25)),
                ('daily_goal_score', models.PositiveIntegerField(default=10)),
                ('localization', models.CharField(max_length=100)),
                ('country_of_origin', models.CharField(max_length=100)),
                ('purpose_language', models.CharField(max_length=100)),
                ('account_created_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
