# Generated by Django 5.2.6 on 2025-09-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_topic_block'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='course_studied',
            field=models.ManyToManyField(related_name='students', to='courses.course'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tasks_confirmed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
