# Generated by Django 5.2.6 on 2025-09-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_course_main_image'),
        ('users', '0004_alter_userprofile_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='course_studied',
            field=models.ManyToManyField(null=True, related_name='students', to='courses.course'),
        ),
    ]
