# Generated by Django 5.2.6 on 2025-10-01 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='ap_time',
            field=models.IntegerField(default=1),
        ),
    ]
