# Generated by Django 6.0.7 on 2026-07-14 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topiclesson',
            name='description',
        ),
        migrations.RemoveField(
            model_name='topiclesson',
            name='title',
        ),
    ]
