# Generated by Django 6.0.7 on 2026-07-20 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_topiclesson_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='short_description',
            field=models.CharField(default='This is the description of this course', max_length=300),
        ),
    ]
