# Generated by Django 5.2.6 on 2025-09-22 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_review_grade_alter_review_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicsBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='topic',
            name='course',
        ),
        migrations.AddField(
            model_name='topic',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.topicsblock'),
        ),
    ]
