# Generated by Django 5.2.6 on 2025-09-22 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_topicsblock_remove_topic_course_topic_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicsblock',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='courses.course'),
        ),
    ]
