# Generated by Django 5.2.6 on 2025-09-22 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_topicsblock_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='courses.topicsblock'),
        ),
    ]
