# Generated by Django 6.0.7 on 2026-08-30 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_rename_userprogress_usermoduleprogress_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermoduleprogress',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_modules', to='courses.module'),
        ),
        migrations.AlterField(
            model_name='usertopicprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_topics', to=settings.AUTH_USER_MODEL),
        ),
    ]
