# Generated by Django 5.2.6 on 2025-09-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_topic_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='essence_html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
