# Generated by Django 5.2.6 on 2025-09-23 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_topic_essence_html'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='body',
            new_name='essence_html',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='essence_html',
        ),
    ]
