# Generated by Django 5.2.6 on 2025-09-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_rename_body_content_essence_html_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/'),
        ),
    ]
