# Generated by Django 6.0.7 on 2026-08-30 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_usercourseprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercourseprogress',
            name='course',
        ),
        migrations.RemoveField(
            model_name='usermoduleprogress',
            name='module',
        ),
        migrations.RemoveField(
            model_name='usertopicprogress',
            name='topic',
        ),
        migrations.AddField(
            model_name='usercourseprogress',
            name='course',
            field=models.ManyToManyField(related_name='user_courses', to='courses.course'),
        ),
        migrations.AddField(
            model_name='usermoduleprogress',
            name='module',
            field=models.ManyToManyField(related_name='user_modules', to='courses.module'),
        ),
        migrations.AddField(
            model_name='usertopicprogress',
            name='topic',
            field=models.ManyToManyField(related_name='user_topics', to='courses.topic'),
        ),
    ]
