# Generated by Django 6.0.7 on 2026-08-30 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_remove_usercourseprogress_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercourseprogress',
            name='course',
        ),
        migrations.AddField(
            model_name='usercourseprogress',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_courses', to='courses.course'),
            preserve_default=False,
        ),
    ]
