# Generated by Django 6.0.7 on 2026-08-30 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_remove_usercourseprogress_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourseprogress',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_progress', to='courses.course'),
        ),
    ]
