# Generated by Django 6.0.7 on 2026-08-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_usercourseprogress_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievments',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='achievment_icons/'),
        ),
        migrations.AddField(
            model_name='achievments',
            name='small_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
