# Generated by Django 6.0.7 on 2026-08-30 14:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_achievments_icon_achievments_small_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Achievments',
            new_name='Achievment',
        ),
    ]
