# Generated by Django 6.0.7 on 2026-08-30 16:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_alter_achievment_user_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usercourseprogress',
            unique_together={('course', 'user')},
        ),
    ]
