# Generated by Django 6.0.7 on 2026-09-02 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_alter_usercourseprogress_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermoduleprogress',
            name='module',
        ),
        migrations.RemoveField(
            model_name='usermoduleprogress',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='usertopicprogress',
            name='topic',
        ),
        migrations.AlterField(
            model_name='usertopicprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='module',
            constraint=models.UniqueConstraint(fields=('course', 'order'), name='unique_module_order_in_course'),
        ),
        migrations.AddConstraint(
            model_name='topic',
            constraint=models.UniqueConstraint(fields=('module', 'order'), name='unique_topic_order_in_module'),
        ),
        migrations.DeleteModel(
            name='UserModuleProgress',
        ),
        migrations.AddField(
            model_name='usertopicprogress',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='courses.topic'),
        ),
    ]
