# Generated by Django 6.0.7 on 2026-09-05 18:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_make_usertopicprogress_topic_required'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usertopicprogress',
            unique_together={('user', 'topic')},
        ),
    ]
