# Generated by Django 6.0.7 on 2026-09-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_alter_usertopicprogress_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourseprogress',
            name='assigned_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
