# Generated by Django 6.0.7 on 2026-09-11 18:23

from django.db import migrations, models


def clear_legacy_external_images(apps, schema_editor):
    Course = apps.get_model('courses', 'Course')
    Course.objects.filter(image__startswith='http://').update(image=None)
    Course.objects.filter(image__startswith='https://').update(image=None)


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_feedback'),
    ]

    operations = [
        migrations.RunPython(clear_legacy_external_images, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, help_text='Обложка курса (рекомендуемое соотношение 16:9)', null=True, upload_to='course_covers/%Y/%m/'),
        ),
    ]
